[env:esp32-s3-epaper]
platform = platformio/espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE
lib_deps =
    lvgl/lvgl@^8.4.0
    knolleary/PubSubClient@^2.8
    sensirion/Sensirion I2C SCD4x@^1.1.0
    adafruit/Adafruit BusIO@^1.17.0
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit SHTC3 Library@^1.0.1
