#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_MEM_SIZE (48U * 1024U)
#define LV_USE_LOG 0
#define LV_USE_PERF_MONITOR 0
#define LV_USE_LABEL 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_USE_THEME_DEFAULT 1

#endif

